name: alghwalbi_core
description: "alghwalbi_core is a Flutter package designed to simplify state management and provide commonly used components and services for Flutter applications."
version: 1.0.0
homepage: https://www.linkedin.com/in/ahmed-abdelrahman-ali-96b249201/

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_animated: ^3.1.0
  beamer: ^1.6.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_html: ^2.1.2
  flutter_markdown: ^0.6.19
  html_editor_enhanced_fork: ^2.5.1
  http: ^0.13.6
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  lifecycle: ^0.8.0
  markdown_editable_textinput: ^2.2.0
  path: ^1.8.3
  path_provider: ^2.1.2
  rive: ^0.12.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: